---
last_check:
  etag:
  version: 1.7.5
  at: 1428373272
checked_completion: true
completion_version: 1.7.5
endpoints:
  https://api.travis-ci.org/:
    access_token:
repos:
  ThatGerber/dfp-ads:
    endpoint: https://api.travis-ci.org/
